/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package command-line-arguments */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
extern size_t _GoStringLen(_GoString_ s);
extern const char *_GoStringPtr(_GoString_ s);
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 3 "backend.go"

#include <stdlib.h>
#include <string.h>

// Forward declarations for C callbacks
typedef void (*lspDiagnosticCallback)(const char* uri, const char* jsonDiagnostics);
typedef void (*lspHoverCallback)(const char* uri, int line, int character, const char* contents);
typedef void (*lspLogCallback)(const char* message);

// Global callback pointers - marked as extern so they're defined in lspclient.cpp
extern lspDiagnosticCallback g_diagnosticCallback;
extern lspHoverCallback g_hoverCallback;
extern lspLogCallback g_logCallback;

// C helper functions for callbacks - declared here, defined in lspclient.cpp
extern void setDiagnosticCallback(lspDiagnosticCallback cb);
extern void setHoverCallback(lspHoverCallback cb);
extern void setLogCallback(lspLogCallback cb);
extern void callDiagnosticCallback(const char* uri, const char* jsonDiagnostics);
extern void callHoverCallback(const char* uri, int line, int character, const char* contents);
extern void callLogCallback(const char* message);

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#if !defined(__cplusplus) || _MSVC_LANG <= 201402L
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
#include <complex>
typedef std::complex<float> GoComplex64;
typedef std::complex<double> GoComplex128;
#endif
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern char* GetConfigDir(void);
extern char* LoadConfigCurrent(void);
extern char* LoadConfigSites(void);
extern GoInt AddSiteAndSetCurrent(char* sitePath);
extern void InitBackend(void);
extern char* ReadFileContent(char* path);
extern GoInt SaveFileContent(char* path, char* content);
extern void FreeString(char* str);
extern GoInt StartHugo(char* repoC);
extern void StopHugo(void);
extern char* ProcessImage(char* srcC, char* repoC, char* docC);
extern char* GetHugoURL(char* filePathC, char* repoPathC);
extern void LSPSetCallbacks(void* diagnosticCb, void* hoverCb, void* logCb);
extern GoInt LSPInitialize(void);
extern void LSPCleanup(void);
extern void LSPSetWorkspaceRoot(char* rootC);
extern void LSPDocumentOpened(char* uriC, char* languageIDC, char* contentC);
extern void LSPDocumentChanged(char* uriC, char* contentC);
extern void LSPDocumentClosed(char* uriC);
extern void LSPRequestHover(char* uriC, GoInt line, GoInt character);
extern GoInt LSPIsEnabled(void);
extern GoInt LSPSetEnabled(GoInt enabled);
extern GoInt LSPStartClients(void);
extern void LSPStopClients(void);
extern char* LSPGetServers(void);
extern GoInt LSPAddServer(char* jsonConfigC);
extern GoInt LSPRemoveServer(char* nameC);
extern GoInt LSPSetServerEnabled(char* nameC, GoInt enabled);

#ifdef __cplusplus
}
#endif
